# Computational graphs

Pytorch encapsulates all the operations. We can keep track of values and calculate gradients automatically. By passing `requires_grad=True` we can access `grad` property of the tensor.

In [1]:
import torch
import numpy as np

In [3]:
x = torch.ones(2,2, requires_grad=True)

In [4]:
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape: {}".format(x.shape))
    print("value: \n{}".format(x))
    

In [5]:
describe(x)

Type: torch.FloatTensor
Shape: torch.Size([2, 2])
value: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [6]:
x.grad is None

True

In [7]:
y = (x+1)*(x+3) +2

In [8]:
describe(y)

Type: torch.FloatTensor
Shape: torch.Size([2, 2])
value: 
tensor([[10., 10.],
        [10., 10.]], grad_fn=<AddBackward0>)


In [10]:
y.grad is None

True

In [11]:
x.grad is None

True

In [12]:
z= y.mean()

In [13]:
describe(z)

Type: torch.FloatTensor
Shape: torch.Size([])
value: 
10.0


In [14]:
x.grad is None

True

In [15]:
z.backward()

In these set of operations we can track the gradient by calling `backward()` function on the end node of computation graph and access the `grad` attribute which is the gradient of the variable.

In order to understand this further lets go through the operations `y` is calculated using `x`. The equation can be seen as arithmatic operation since `x` is a `2x2` matric, `y` is calculated using matrix multiplication and  other arithmatic operations. `z` is caculated by calling `mean()` function. `backward()` function computes the gradient of current tensor w.r.t. graph leaves. (here `x` is the computation graph leaf).

In [16]:
x.grad

tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])