In [1]:
import torch
import numpy as np

# Creating Tensors

In [5]:
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape: {}".format(x.shape))
    print("value: \n{}".format(x))
    

In [9]:
describe(torch.Tensor(3,2))


Type: torch.FloatTensor
Shape: torch.Size([3, 2])
value: 
tensor([[6.1368e-37, 0.0000e+00],
        [1.4013e-45, 0.0000e+00],
        [6.3805e-37, 0.0000e+00]])


## create random tensor

In [10]:
describe(torch.rand(2,3))
describe(torch.randn(2,3))


Type: torch.FloatTensor
Shape: torch.Size([2, 3])
value: 
tensor([[0.6512, 0.6514, 0.2838],
        [0.7903, 0.3043, 0.1813]])
Type: torch.FloatTensor
Shape: torch.Size([2, 3])
value: 
tensor([[ 0.3043, -1.1281,  0.2105],
        [ 0.0271,  0.8911, -2.2315]])


In [13]:
x = torch.zeros(2,3)
describe(x)

Type: torch.FloatTensor
Shape: torch.Size([2, 3])
value: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [14]:
x.fill_(5)
describe(x)

Type: torch.FloatTensor
Shape: torch.Size([2, 3])
value: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [15]:
x= torch.ones(2,3)
describe(x)

Type: torch.FloatTensor
Shape: torch.Size([2, 3])
value: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [17]:
x= torch.Tensor([[1,2,3],[2,3,4]])
describe(x)

Type: torch.FloatTensor
Shape: torch.Size([2, 3])
value: 
tensor([[1., 2., 3.],
        [2., 3., 4.]])


## Using from_numpy() function

In [20]:
nump_arr = np.random.rand(2,3)
nump_arr

array([[0.92696343, 0.30059361, 0.96526695],
       [0.34390173, 0.35545433, 0.65300339]])

In [23]:
describe(torch.from_numpy(nump_arr))

Type: torch.DoubleTensor
Shape: torch.Size([2, 3])
value: 
tensor([[0.9270, 0.3006, 0.9653],
        [0.3439, 0.3555, 0.6530]], dtype=torch.float64)


# Types and size

In [25]:
x = torch.FloatTensor([[2,3,54,1],[1,232,1,43]])
describe(x)

Type: torch.FloatTensor
Shape: torch.Size([2, 4])
value: 
tensor([[  2.,   3.,  54.,   1.],
        [  1., 232.,   1.,  43.]])


In [26]:
x = x.long()
describe(x)

Type: torch.LongTensor
Shape: torch.Size([2, 4])
value: 
tensor([[  2,   3,  54,   1],
        [  1, 232,   1,  43]])


In [28]:
x = torch.tensor([[2,3,54,1],[1,232,1,43]], dtype=torch.int64)
describe(x)

Type: torch.LongTensor
Shape: torch.Size([2, 4])
value: 
tensor([[  2,   3,  54,   1],
        [  1, 232,   1,  43]])


In [29]:
x=x.float()
describe(x)

Type: torch.FloatTensor
Shape: torch.Size([2, 4])
value: 
tensor([[  2.,   3.,  54.,   1.],
        [  1., 232.,   1.,  43.]])


# Tensor operations



In [31]:
x = torch.tensor([[2,3,54,1],[1,232,1,43]], dtype=torch.int64)
describe(x+x)

Type: torch.LongTensor
Shape: torch.Size([2, 4])
value: 
tensor([[  4,   6, 108,   2],
        [  2, 464,   2,  86]])


In [37]:
describe(x*2)

Type: torch.LongTensor
Shape: torch.Size([2, 4])
value: 
tensor([[  4,   6, 108,   2],
        [  2, 464,   2,  86]])


In [45]:
x=x.float()
describe(x/4)

Type: torch.FloatTensor
Shape: torch.Size([2, 4])
value: 
tensor([[ 0.5000,  0.7500, 13.5000,  0.2500],
        [ 0.2500, 58.0000,  0.2500, 10.7500]])


In [48]:
y = torch.arange(100)
describe(y)

Type: torch.LongTensor
Shape: torch.Size([100])
value: 
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])


In [49]:
describe(y.view(10,10))

Type: torch.LongTensor
Shape: torch.Size([10, 10])
value: 
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])


In [54]:
describe(torch.sum(y.view(10,10), dim=0))

Type: torch.LongTensor
Shape: torch.Size([10])
value: 
tensor([450, 460, 470, 480, 490, 500, 510, 520, 530, 540])


In [57]:
w= y.view(10,10)
# w= torch.transpose(w,0,1)
w=w.transpose(0,1)
describe(w)

Type: torch.LongTensor
Shape: torch.Size([10, 10])
value: 
tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92],
        [ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93],
        [ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
        [ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
        [ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96],
        [ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97],
        [ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98],
        [ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99]])


## Indexing, slicing and joining

In [64]:
w[2:5,4:10]

tensor([[42, 52, 62, 72, 82, 92],
        [43, 53, 63, 73, 83, 93],
        [44, 54, 64, 74, 84, 94]])

In [69]:
describe(w[5,:1])

Type: torch.LongTensor
Shape: torch.Size([1])
value: 
tensor([5])


In [75]:
indexes = torch.LongTensor([3,2, 9])
torch.index_select(w, dim=0,index=indexes)

tensor([[ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93],
        [ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92],
        [ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99]])

In [80]:
describe(torch.cat([x,x] , dim=1))

Type: torch.FloatTensor
Shape: torch.Size([2, 8])
value: 
tensor([[  2.,   3.,  54.,   1.,   2.,   3.,  54.,   1.],
        [  1., 232.,   1.,  43.,   1., 232.,   1.,  43.]])


In [85]:
describe(torch.stack([x,x]))

Type: torch.FloatTensor
Shape: torch.Size([2, 2, 4])
value: 
tensor([[[  2.,   3.,  54.,   1.],
         [  1., 232.,   1.,  43.]],

        [[  2.,   3.,  54.,   1.],
         [  1., 232.,   1.,  43.]]])


In [87]:
a = torch.arange(100).view(10,10)

In [90]:
b = torch.ones(10,10)
b[:,1:3] +=1
describe(b)

Type: torch.FloatTensor
Shape: torch.Size([10, 10])
value: 
tensor([[1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
        [1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
        [1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
        [1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
        [1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
        [1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
        [1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
        [1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
        [1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
        [1., 2., 2., 1., 1., 1., 1., 1., 1., 1.]])


In [92]:
torch.mm(a.long(),b.long())

tensor([[  45,   90,   90,   45,   45,   45,   45,   45,   45,   45],
        [ 145,  290,  290,  145,  145,  145,  145,  145,  145,  145],
        [ 245,  490,  490,  245,  245,  245,  245,  245,  245,  245],
        [ 345,  690,  690,  345,  345,  345,  345,  345,  345,  345],
        [ 445,  890,  890,  445,  445,  445,  445,  445,  445,  445],
        [ 545, 1090, 1090,  545,  545,  545,  545,  545,  545,  545],
        [ 645, 1290, 1290,  645,  645,  645,  645,  645,  645,  645],
        [ 745, 1490, 1490,  745,  745,  745,  745,  745,  745,  745],
        [ 845, 1690, 1690,  845,  845,  845,  845,  845,  845,  845],
        [ 945, 1890, 1890,  945,  945,  945,  945,  945,  945,  945]])